In [ ]:

# Applied Statistics Lab
# Creating series from array
import pandas as pd
import numpy as np

# **Exercise 1**


In [6]:
import pandas as pd
arr=np.array(['D','E','V','I','L'])
ga=pd.Series(arr)
print(ga)

0    D
1    E
2    V
3    I
4    L
dtype: object


In [7]:
# Creating a dataframe using list
# Create a list
a=['Devansh','Amit']
#Create a dataframe
df=pd.DataFrame(a)
print(df)

         0
0  Devansh
1     Amit


In [8]:
# using pandas map function
a=pd.Series(['Devansh','Adi','Humble','Amit'])
a.map({'Devansh':True,'Amit':True})

0    True
1     NaN
2     NaN
3    True
dtype: object

In [9]:
# ONE ANOTHER EXAMPLE
a=pd.Series(['Devansh','Amit','Sid','Sanoop'])
a.map({'Devansh':True})
a.map('i like {}'.format, na_action='ignore')

0    i like Devansh
1       i like Amit
2        i like Sid
3     i like Sanoop
dtype: object

In [11]:
# conversion of series object to the dataframe
# example 1
g=pd.Series(["Devansh","Sid","Yash"],name="Row")
g.to_frame()

Row
0  Devansh
1      Sid
2     Yash

In [12]:
# example 2
gst=['Devansh','Amit','Yash','Ayush']
id=[111,112,113,114]
gst_series=pd.Series(gst)
id_series=pd.Series(id)
frame={'Gst':gst_series,'ID':id_series}
result=pd.DataFrame(frame)
print(result)

       Gst   ID
0  Devansh  111
1     Amit  112
2     Yash  113
3    Ayush  114


# **Exercise 2**

In [ ]:
# create an empty dataframe in pandas
import pandas as pd
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [13]:
# create a dataframe in pandas on list
list=['Yashpal','Labour']
df=pd.DataFrame(list)
print(df)

         0
0  Yashpal
1   Labour


In [ ]:
# create a dataframe from dict of ndarrays/lists
info={'ID':[101,102,103],'Department':['B.Sc','B.Tech','M.Tech']}
df=pd.DataFrame(info)
print(df)

    ID Department
0  101       B.Sc
1  102     B.Tech
2  103     M.Tech


In [ ]:
# craete a DataFrame from dict of series:
sr={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
df=pd.DataFrame(sr)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8


In [ ]:
# select a column from the dataframe
sr={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
df=pd.DataFrame(sr)
print(df['one'])

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    NaN
h    NaN
Name: one, dtype: float64


In [ ]:
# add any new column to an existing DataFrame
sr={'one':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
df=pd.DataFrame(sr)
# add a new column
print("add new column by passing series")
df['three']=pd.Series([20,40,60],index=['a','b','c'])
print(df)
print("add new column using existing DataFrame columns")
df['four']=df['one']+df['three']
print(df)

add new column by passing series
   one  two  three
a  1.0    1   20.0
b  2.0    2   40.0
c  3.0    3   60.0
d  4.0    4    NaN
e  5.0    5    NaN
f  6.0    6    NaN
g  NaN    7    NaN
h  NaN    8    NaN
add new column using existing DataFrame columns
   one  two  three  four
a  1.0    1   20.0  21.0
b  2.0    2   40.0  42.0
c  3.0    3   60.0  63.0
d  4.0    4    NaN   NaN
e  5.0    5    NaN   NaN
f  6.0    6    NaN   NaN
g  NaN    7    NaN   NaN
h  NaN    8    NaN   NaN


In [ ]:
# deletation of the column from the existing DataFrame
sr={'one':pd.Series([1,2],index=['a','b']),'two':pd.Series([1,2,3],index=['a','b','c'])}
df=pd.DataFrame(sr)
print("DataFrame:")
print(df)
# using del function
print("delete the first column:")
del df['one']
print(df)
# using pop function
print("delete the another column")
df.pop('two')
print(df)

DataFrame:
   one  two
a  1.0    1
b  2.0    2
c  NaN    3
delete the first column:
   two
a    1
b    2
c    3
delete the another column
Empty DataFrame
Columns: []
Index: [a, b, c]


In [ ]:
# selection of rows by using different methods
# SELECTION BY LABEL
import pandas as pd
info={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),'two':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])}
df=pd.DataFrame(info)
print(df.loc['b'])

one    2.0
two    2.0
Name: b, dtype: float64


In [ ]:
# selection by integer location
info={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),'two':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])}
df=pd.DataFrame(info)
print(df.iloc[3])

one    4.0
two    4.0
Name: d, dtype: float64


In [ ]:
# Slice rows
info={'one':pd.Series([1,2,3,4,5],index=['a','b','c','d','e']),'two':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])}
df=pd.DataFrame(info)
print(df[2:5])

   one  two
c  3.0    3
d  4.0    4
e  5.0    5


In [ ]:
# Addition of rows
import numpy as np
import pandas as pd
g=pd.DataFrame([[7,8],[9,10]],columns=['x','y'])
g2=pd.DataFrame([[11,12],[13,14]],columns=['x','y'])
g=g.append(g2)
print(g)

    x   y
0   7   8
1   9  10
0  11  12
1  13  14


<ipython-input-60-27199067d107>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  g=g.append(g2)


In [ ]:
# Deletion of rows
a_info=pd.DataFrame([[4,5],[6,7]],columns=['x','y'])
b_info=pd.DataFrame([[8,9],[10,11]],columns=['x','y'])
a_info=a_info.append(b_info)
# drop rows with label 0
a_info=a_info.drop(0)

<ipython-input-61-0e45aa2f0d39>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a_info=a_info.append(b_info)


# **Exercise 3**

In [ ]:
# Add a column to dataframe column
aa=pd.read_csv("/content/iris.csv")
aa.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
# Add any new column
aa=pd.read_csv("/content/iris.csv")
aa["Age"]="24"
aa.head()

sepal.length  sepal.width  petal.length  petal.width variety Age
0           5.1          3.5           1.4          0.2  Setosa  24
1           4.9          3.0           1.4          0.2  Setosa  24
2           4.7          3.2           1.3          0.2  Setosa  24
3           4.6          3.1           1.5          0.2  Setosa  24
4           5.0          3.6           1.4          0.2  Setosa  24

In [ ]:
aa=pd.read_csv("/content/iris.csv")
aa.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
# Add a new column name "course" into an existing "aa" csv file using insert method
aa=pd.read_csv("/content/iris.csv")
aa.insert(2,column="course",value="B.Sc")
aa.head()

sepal.length  sepal.width course  petal.length  petal.width variety
0           5.1          3.5   B.Sc           1.4          0.2  Setosa
1           4.9          3.0   B.Sc           1.4          0.2  Setosa
2           4.7          3.2   B.Sc           1.3          0.2  Setosa
3           4.6          3.1   B.Sc           1.5          0.2  Setosa
4           5.0          3.6   B.Sc           1.4          0.2  Setosa

# Exercise 5

In [ ]:
# creating index
data=pd.read_csv("/content/iris.csv")
data

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
# making data frame from csv file
info=pd.read_csv("/content/iris.csv",index_col="sepal.length")
# retrieving multiple columns by indexing operator
a=info[["sepal.width","petal.length"]]
print(a)

              sepal.width  petal.length
sepal.length                           
5.1                   3.5           1.4
4.9                   3.0           1.4
4.7                   3.2           1.3
4.6                   3.1           1.5
5.0                   3.6           1.4
...                   ...           ...
6.7                   3.0           5.2
6.3                   2.5           5.0
6.5                   3.0           5.2
6.2                   3.4           5.4
5.9                   3.0           5.1

[150 rows x 2 columns]


In [ ]:
# EXAMPLE 2
# making data frame from csv file
info=pd.read_csv("/content/iris.csv",index_col="sepal.length")
# retrieving multiple columns by indexing operator
a=info[["sepal.width"]]
print(a)

              sepal.width
sepal.length             
5.1                   3.5
4.9                   3.0
4.7                   3.2
4.6                   3.1
5.0                   3.6
...                   ...
6.7                   3.0
6.3                   2.5
6.5                   3.0
6.2                   3.4
5.9                   3.0

[150 rows x 1 columns]


In [14]:
#set index
info=pd.DataFrame({'Name':['Devansh','Sachin','Yash','Karan'],
'Year':[2011,1012,2013,1014],
'Leaves':[1,2,3,4]})
info
info.set_index('Name')
info.set_index(['Year','Name'])
info.set_index([pd.Index([1,2,3,4]),'Year'])
a=pd.Series([1,2,3,4])
info.set_index([a,a**2])

Name  Year  Leaves
1 1   Devansh  2011       1
2 4    Sachin  1012       2
3 9      Yash  2013       3
4 16    Karan  1014       4

In [ ]:
#EXAMPLE 1
pd.MultiIndex(levels=[[np.nan,None,pd.NaT,128,2]],
codes=[[0,-1,1,2,3,4]])



MultiIndex([(nan,),
            (nan,),
            (nan,),
            (nan,),
            (128,),
            (  2,)],
           )

In [15]:
# RESET INDEX
info=pd.DataFrame([('Devansh','C'),
('Sid','Java'),
('Amit','Python'),
('Karan','C++')],
index=[1,2,3,4],
columns=('Name','Language'))
info
info.reset_index()

index     Name Language
0      1  Devansh        C
1      2      Sid     Java
2      3     Amit   Python
3      4    Karan      C++

# **EXERCISE 7**

In [ ]:
import array

In [ ]:
arr=array.array('l',[2,4,6,8,10,12])

In [ ]:
#print the original array
print("New created array", end="")

New created array

In [ ]:
for l in range(0,5):
  print(arr[l],end="")
  print('\r')

2
4
6
8
10


In [ ]:
import pandas as pd

In [16]:
#dictinory of lists
dict = {'name':["Sid","Yash","Prince","Rajesh"],
        'age':["28","39","34","36"]}

In [17]:
 info = pd.DataFrame(dict,index = [True, True, False, True])
print(info)

         name age
True      Sid  28
True     Yash  39
False  Prince  34
True   Rajesh  36


In [18]:
# accesing a datafram using .loc[] function
print(info.loc[True])

        name age
True     Sid  28
True    Yash  39
True  Rajesh  36


In [ ]:
import numpy as np

In [ ]:
arr = np.arange(16)
print("The original array is:\n",arr)
#shape array with 2 rows and 8 columns
arr = np.arange(16).reshape(2,8)
print("\nreshaped array:\n",arr)
#shape arary with 2 rows and 8 columns
arr = np.arange (16).reshape(8,2)
print("\nreshaped array:\n",arr)


The original array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshaped array:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

reshaped array:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


# **Exercise 8**

In [19]:
 import numpy as np
 a = np.array([1, 2, 3]) #create a rank 1 array
 print(type(a))
 print(a.shape)
 print(a[0], a[1], a[2])
a[0] = 5
print(a)
b = np.array([[1,2,3],[4,5,.6]])  # create a rank 2 array
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 2])
# numpy also provides many functions to create arrays:
a = np.zeros((2,2)) # create an array of all zeros
print(a)

b = np.ones((1,2))  #create an array of all ones
print(b)

c = np.full((2,2),  7)  # create a constant array
print(c)

d = np.eye(2)  # create a 2x2 identity matrix
print(d)

e = np.random.random((2,2))  # create an array filled with random values
print(e)



<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1.0 2.0 0.6
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.02126868 0.42097143]
 [0.93279475 0.55606921]]


# **ARRAY INDEXING**

In [28]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a[0, 1])
b[0, 0] = 77 # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77


In [29]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]  # rank 1 view of the second row of a
row_r2 = a[:, 1:2] # rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# we can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)



[5 6 7 8] (4,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [30]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
# element from the source array:
print(a[[0, 0], [1, 1]])
# equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)

# create an array of indices
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])
a[np.arange(4), b] +=10
print(a)



[2 2]
[2 2]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [31]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [32]:
# DATATYPES
import numpy as np
x = np.array([1, 2])
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
x = np.array([1, 2],  dtype=np.int64)
print(x.dtype)

int64
float64
int64


In [33]:
# ARRAY MATH
import numpy as np
x = np.array([[1,2], [3,4]] , dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [34]:
import numpy as np
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11, 121])
#Inner product of vectors; both produce 219
print (v.dot (w))
print(np.dot (v, w))

1309
1309


In [35]:
# Matrix/vector product; both produce the rank 1 array
# [29 67]
print (x.dot (v))
print (np.dot (x, v))
# Matrix matrix product; both produce the rank 2 array
# [[19 22]
# [43 50]]
print (x.dot (y))
print (np.dot (x, y))
# Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:
import numpy as np
np.array([[1,2], [3,4]])
print(np.sum (x))
# Compute sum of all elements; printa 10"
print (np.sum(x, axis=0))
# prints "(4 6)"
# Compute sum of each column:
print(np.sum(x, axis=1))
# Compute sum of each row:
# prints "[3 71]"

[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
10
[4 6]
[3 7]


In [36]:
import numpy as np
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)
v = np.array([1,2,3])
print(v)
print(v.T)



[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
